services:
  db:
    image: mysql:8.0
    container_name: kinebot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hero_factory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: hero_factory_backend
    restart: always
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
    depends_on:
      - db

volumes:
  mysql_data: