name: Fullstack CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install & Test Frontend
        run: |
          npm install
          npm test

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Subir containers de teste
        run: docker-compose up -d

      - name: Rodar Testes do Backend
        run: docker-compose exec -T backend npm test 

      - name: Derrubar containers
        if: always()
        run: docker-compose down